---
title: "Numerical analysis of cave fauna of Greece"
author: "Hellenic Institute of Speleological Research"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
link-citations: yes
bibliography: packages_used.bib
site: bookdown::bookdown_site
biblio-style: apalike
---


```{r, warning=FALSE, message=FALSE, echo=FALSE}
### Working Directory

#setwd("C:/Users/inikoloudakis/Dropbox/INSPEE Team Folder/Conservation of the cave fauna of Greece - MAVA/Cave_Fauna_database/Cave_Fauna_Database_Analysis")

# Data manipulation packages
library(readxl)
library(readr)
library(ggplot2)
library(scales)
library(gridExtra)
library(grid)
library(reshape2)
library(dplyr)
library(knitr)
library(tidyr)
library(httr)
library(broom)
library(stringr)

## Data for species

library(rredlist)
library(taxize)
library(rgbif)
library(ISOcodes)
library(spocc)

# Spatial analysis packages

# x <- c("spocc","isocodes","rgbif","taxize","rredlist","raster","RColorBrewer","ggmap", "rgdal", "rgeos", "maptools", "tmap","Rcpp","sp")
# #install.packages(x) # warning: uncommenting this may take a number of minutes
# lapply(x, library, character.only = TRUE)
library(RColorBrewer)
library(ggmap)
library(rgdal)
library(geosphere)
library(GISTools)
library(leaflet)
library(rgeos)
library(maptools)
#library(tmap)
library(Rcpp)
library(sp)
library(raster) ##Load the Raster Library

# Species statistics

library(red)
library(vegan)

packages <- c("readxl","readr","ggplot2","scales","gridExtra","dplyr", "knitr", "tidyr","RColorBrewer","ggmap","rgdal","rgeos","maptools","tmap","Rcpp","sp","raster","broom","red","vegan")

write_bib(x = packages,file = "packages_used.bib")

```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
# Store the file names of the Data folder
 
 data_files <- list.files(path = "Data")
 
 # Data import from Database Export, the files are choosen automatically based on their name. The folder Data must contain only the latest data files.
 Cave_References <- read_delim(file = paste0("Data/",grep("Cave_References",data_files,value = TRUE)),delim = "\t")
 
 caves <- read_delim(file = paste0("Data/",grep("Caves",data_files,value = TRUE)),delim = "\t")
 
 census <- read_delim(file = paste0("Data/",grep("Census_\\d",data_files,value = TRUE)),delim = "\t")
 
 Census_references <- read_delim(file = paste0("Data/",grep("Census_references",data_files,value = TRUE)),delim = "\t")
 
species <- read_delim(file = paste0("Data/",grep("Species_",data_files,value = TRUE)),delim = "\t") %>% mutate(Classification=gsub(pattern="\\?",replacement = "",x = Classification))# Data import from Database Export

```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
census$species_epithet <- as.character(lapply(strsplit(as.character(census$Species), split=" "), "[", n=2))

census_all_species <- census %>% left_join(species,by=c("Species"="Species_Full_Name"))

census_all_species_all_caves <- census_all_species %>% dplyr::select(-Cave_Name) %>% left_join(caves, by=c("Cave_ID"="Cave_ID"))

census_long_str_man <- strsplit(x = census_all_species$Reference_Short,split = "|",fixed=TRUE)
census_long_str_man_id <- strsplit(x = census_all_species$Reference_ID,split = "|",fixed=TRUE)

census_long_man <- data_frame(ReferenceShort=unlist(census_long_str_man),reference_id=unlist(census_long_str_man_id),CaveName=rep.int(census_all_species$Cave_Name,times = sapply(census_long_str_man,length)),Cave_ID=rep.int(census_all_species$Cave_ID,times = sapply(census_long_str_man,length)),Census_id=rep.int(census_all_species$Census_ID,times = sapply(census_long_str_man,length)),Species=rep.int(census_all_species$Species,times = sapply(census_long_str_man,length))) %>% group_by(ReferenceShort,Cave_ID,CaveName,Species,Census_id) %>% summarise(n=n()) %>% ungroup() %>% mutate(Species=trimws(Species,"r"))

```


## Q Mode

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(cluster)
library(vegan)
#library(FD)
library(gclus)
library(ggdendro)


```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
caves_crete <- caves %>% filter(Region=="Kriti")

troglobiont <- species %>% filter(Classification=="Troglobiont")

caves_species_wide <- census_long_man %>% dplyr::select(Cave_ID,Species) %>% distinct() %>% filter(Species %in% troglobiont$Species_Full_Name) %>% mutate(presence=1) %>% spread(value = presence,key = Species,fill = 0)

rownames(caves_species_wide) <- caves_species_wide$Cave_ID

caves_species_wide <- caves_species_wide %>% dplyr::select(-Cave_ID)

```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
caves_species_wide_distance <- vegdist(caves_species_wide,binary = T,method = "jaccard")
caves_species_wide_distance_t <- vegdist(t(caves_species_wide),binary = T,method = "jaccard")


caves_species_wide_distance_ma <- as.matrix(caves_species_wide_distance)

row.order <- order.dendrogram(as.dendrogram(hclust(caves_species_wide_distance))) # clustering
#col.order <- order.dendrogram(as.dendrogram(hclust(caves_species_wide_distance_t)))

caves_species_wide_distance_ma_df <- as.data.frame(caves_species_wide_distance_ma[row.order,row.order])

caves_species_wide_distance_ma_df$cave1 <- rownames(caves_species_wide_distance_ma_df)

caves_species_wide_distance_df <- gather(caves_species_wide_distance_ma_df,cave2,value = distance,-cave1)

#caves_species_wide_distance_df$item1 <- factor(x=caves_species_wide_distance_df$item1,levels=row.order,ordered = TRUE)
#caves_species_wide_distance_df$item2 <- factor(x=caves_species_wide_distance_df$item2,levels=col.order,ordered = TRUE)

caves_species_wide_distance_tidy <- tidy(caves_species_wide_distance)
```

## Dendrograms

```{r}
plot(hclust(caves_species_wide_distance,method = "ward.D"),cex=0.5)
```

```{r}

cluster_caves_species_wide_distance <- hclust(caves_species_wide_distance,method = "ward.D")

dendro <- as.dendrogram(cluster_caves_species_wide_distance)


ddata <- dendro_data(dendro, type="rectangle")
labels_dendro <- label(ddata) %>% mutate(label_numeric=as.numeric(label)) %>% left_join(caves, by=c("label_numeric"="Cave_ID"))
last_branches <- ddata$segments %>% filter(yend == 0) %>% left_join(labels_dendro, by = "x") # merge segmants with labels

ggplot() + 
  geom_segment(data = segment(ddata),aes(x=x, y=y, xend=xend, yend=yend)) + 
  geom_segment(data = last_branches, aes(x=x, y=y.x, xend=xend, yend=yend, color = Region)) +
  geom_text(data = ddata$labels, aes(x, y, label = label, colour=labels_dendro$Region), hjust = 1, angle = 90, size = 1)+
  scale_colour_manual(values = colorRampPalette(c("orangered2","palegreen3","skyblue1","slateblue1","pink2","goldenrod1","slategray2"),space="Lab")( 14 ))+
  ggtitle("Caves hierarchical clustering")+
  theme_dendro()

ggsave("caves_species_jaccard_distance_dendro.png", plot = last_plot(), device = "png",width = 20,height = 20,units = "in", dpi = 300,path = "Plots/")
```


## Heatmaps

```{r, warning=FALSE, message=FALSE, echo=FALSE}
ggplot() +
  geom_tile(data = caves_species_wide_distance_df, aes(x = cave1, y = cave2,fill = distance)) +
  scale_fill_gradient(low = "red", high = "white") +
  ylab("Caves") +
  xlab("Caves") +
  theme_bw() +
  labs(fill = "Jaccard distance")+
  theme(axis.ticks = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1,size = 2),axis.text.y = element_text(angle = 45, hjust = 1,size = 2))

ggsave("caves_species_jaccard_distance.png", plot = last_plot(), device = "png",width = 20,height = 20,units = "in", dpi = 300,path = "Plots/")

```

```{r}
heatmap <- heatmap(caves_species_wide_distance_ma,col = heat.colors(256))

```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
ggplot() +
  geom_tile(data = caves_species_wide_distance_tidy, aes(x = item1, y = item2,fill = distance)) +
  scale_fill_gradient(low = "red", high = "white") +
  ylab("Caves") +
  xlab("Caves") +
  theme_bw() +
  labs(fill = "Jaccard distance")

```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
caves_species_wide_distance_df_hist <- caves_species_wide_distance_df %>% group_by(distance) %>% summarise(n=n())

ggplot(data=caves_species_wide_distance_df_hist)+
  geom_line(aes(x=distance, y= n),color="purple",show.legend = F)+
  geom_point(aes(x=distance, y= n),color="purple",show.legend = F, size=1)+
  theme_bw()+
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank())

```

## Example
```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(vegan)
library(ggplot2)
library(reshape2)

# set binary: TRUE if presence/absence data
#             FALSE if abundance data
binary <- TRUE

m <- 500
n <- m
set.seed(12345)
if(binary == TRUE){
  # Create matrix with random 0/1 values
  x <- sample.int (2, m*n, TRUE)-1L
  dim(x) <- c(m,n)  
} else {
  # Or create matrix with values in the range 0-10
  x <- matrix(round(runif(n*m, 0, 10)), nrow = m, ncol = n)  
}

#### Test the standardization 
jaccard <- vegdist(x, method = "jaccard", binary = FALSE)
jaccard.stand <- vegdist(x, method = "jaccard", binary = TRUE)
### Are they equal?
all(jaccard == jaccard.stand)

jacc.dft <- tidy(jaccard)


### Plot for safety
jacc.df <- melt(cbind(jaccard, jaccard.stand))
ggplot(jacc.df, aes(x = value, fill = Var2, colour = Var2)) + 
  geom_histogram(alpha = 0.2, position = "identity", binwidth = 0.01)
```

## Species - Area Relationship

## Species accumulation curve

```{r, warning=FALSE, message=FALSE, echo=FALSE}

species_accumulation <- census %>% distinct(Species,Cave_ID) %>% mutate(Duplicates=duplicated(Species), species_epithet= as.character(lapply(strsplit(as.character(Species), split=" "), "[", n=2))) %>% filter(species_epithet!="sp.") %>% mutate(.,First_occurance=if_else(Duplicates=="FALSE",1,0)) %>% filter(First_occurance==1) %>% group_by(Cave_ID) %>% mutate(First_occurance_per_cave=sum(First_occurance))# %>% group_by(First_occurance_per_cave) %>% summarise(number_of_caves=n()) #mutate(Cumulative_occurance= cumsum(First_occurance))

species_accumulation_wide <- census %>% mutate(species_epithet= as.character(lapply(strsplit(as.character(Species), split=" "), "[", n=2))) %>% filter(species_epithet!="sp.") %>% dplyr::select(Cave_ID,Species) %>% distinct() %>% mutate(presence=1) %>% spread(value = presence,key = Species,fill = 0) %>% tibble::column_to_rownames(.,var="Cave_ID")  # %>% dplyr::select(-Cave_ID)

acc <- specaccum(species_accumulation_wide,"random")

specpool_m <- poolaccum(x = species_accumulation_wide)

specpool_m_summary <- summary(specpool_m)

specpool_m_summary_chao <- as.data.frame(specpool_m_summary$chao)

specpool_m_summary_bootstrap <- as.data.frame(specpool_m_summary$boot)

Vspecpool_m_data <- as.data.frame(specpool_m$means)
data_accumutation_c <- data.frame(Sites=acc$sites, Richness=acc$richness, SD=acc$sd)

ggplot() +
  #geom_point(data=data_accumutation_c, aes(x=Sites, y=Richness)) +
  geom_line(data=data_accumutation_c, aes(x=Sites, y=Richness, color="Accumulation curve")) +
  #geom_line(data=Vspecpool_m_data, aes(x=, y=increasing)) +
  geom_line(data=specpool_m_summary_bootstrap, aes(x=N, y=Bootstrap,color="Bootstrap extrapolation")) +
  #geom_line(data=specpool_m_summary_chao, aes(x=N, y=Chao, color="Chao extrapolation")) +
  geom_ribbon(data=data_accumutation_c ,aes(x=Sites, ymin=(Richness-2*SD),ymax=(Richness+2*SD)),alpha=0.2)+
  geom_ribbon(data=specpool_m_summary_bootstrap ,aes(x=N, ymin=(Bootstrap-2*Std.Dev),ymax=(Bootstrap+2*Std.Dev)),alpha=0.2)+
  #geom_ribbon(data=specpool_m_summary_chao ,aes(x=N, ymin=(Chao-2*Std.Dev),ymax=(Chao+2*Std.Dev)),alpha=0.2)+
  scale_y_continuous(breaks = seq(0,1100,100),limits = c(0,1100))+
  scale_x_continuous(breaks = seq(0,500,50),limits = c(0,500))+
  scale_color_manual(name="",values = c("Accumulation curve"="black","Bootstrap extrapolation"="pink","Chao extrapolation"="blue"))+
  ggtitle("Cave fauna of Greece accumulation curve")+
  #coord_equal()+
  labs(x="Caves", y= "Number of species")+
  theme_bw()+
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),legend.position = c(0.18,0.86))

ggsave("species_accumulation_curve.jpeg", plot = last_plot(), device = "jpeg", dpi = 300,path = "Plots/")


```


## Species Distribution Modeling

## Species Distribution Elavation Gradient

